# Generated by Django 6.0.2 on 2026-04-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
