# Generated by Django 6.0.2 on 2026-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AELAF MART', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_branding/')),
            ],
            options={
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
